name: CI

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE my_db;' -uroot -proot
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install deb dependencies
        run: |
          sudo apt update
          sudo apt install pandoc
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install pycodestyle coverage pytest pypandoc
          python setup.py install
      - name: Run pycodestyle
        run: |
          pycodestyle --exclude=venv --ignore=E501 .
      - name: Run pytest
        run: |
          coverage run --source=. -m pytest
      - name: Generate coverage report
        run: |
          coverage report -m
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
